version: '3'
services:
  app:
    image: zharif/genics-api
    ports:
      - '3000:3000'
    environment:
      - MONGO_DB=mongodb://mongodb:27017/mydatabase
      - PORT=3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'